In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob

In [126]:
# Merging csv files (without repeating header)
interesting_files = glob.glob("raw_data/*.csv") 
df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))
df

C:\Users\Loba\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

,ARR_DELAY,ARR_DELAY_NEW,ARR_TIME,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_DELAY_NEW,DEP_TIME,DEST,DEST_AIRPORT_ID,...,NAS_DELAY,OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,SECURITY_DELAY,Unnamed: 23,WEATHER_DELAY
0,-1.0,0.0,417.0,NaN,1,-1.0,0.0,54.0,DEN,11292,...,NaN,408,F9,LAX,12892,"Los Angeles, CA",California,NaN,NaN,NaN
1,-32.0,0.0,933.0,NaN,1,-7.0,0.0,623.0,ORD,13930,...,NaN,1286,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN,NaN
2,5.0,5.0,824.0,NaN,1,22.0,22.0,622.0,LAS,12889,...,NaN,1679,F9,MCO,13204,"Orlando, FL",Florida,NaN,NaN,NaN
3,7.0,7.0,1436.0,NaN,1,2.0,2.0,912.0,MEM,13244,...,NaN,1990,F9,LAS,12889,"Las Vegas, NV",Nevada,NaN,NaN,NaN
4,212.0,212.0,2029.0,210.0,1,213.0,213.0,1852.0,LAS,12889,...,0.0,1999,F9,MEM,13244,"Memphis, TN",Tennessee,0.0,NaN,0.0
5,89.0,89.0,959.0,0.0,1,-10.0,0.0,601.0,LGA,12953,...,89.0,1462,F9,ATL,10397,"Atlanta, GA",Georgia,0.0,NaN,0.0
6,125.0,125.0,1334.0,0.0,1,91.0,91.0,1050.0,CVG,11193,...,119.0,649,F9,LGA,12953,"New York, NY",New York,0.0,NaN,6.0
7,116.0,116.0,1527.0,11.0,1,130.0,130.0,1430.0,DEN,11292,...,99.0,649,F9,CVG,11193,"Cincinnati, OH",Kentucky,0.0,NaN,0.0
8,-22.0,0.0,34.0,NaN,1,-6.0,0.0,1953.0,ATL,10397,...,NaN,426,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN,NaN
9,-1.0,0.0,1009.0,NaN,1,-1.0,0.0,629.0,TPA,15304,...,NaN,1206,F9,MKE,13342,"Milwaukee, WI",Wisconsin,NaN,NaN,NaN
10,-4.0,0.0,1336.0,NaN,1,-4.0,0.0,1056.0,BUF,10792,...,NaN,1228,F9,TPA,15304,"Tampa, FL",Florida,NaN,NaN,NaN
11,-2.0,0.0,1718.0,NaN,1,-1.0,0.0,1429.0,TPA,15304,...,NaN,1231,F9,BUF,10792,"Buffalo, NY",New York,NaN,NaN,NaN
12,10.0,10.0,2012.0,NaN,1,1.0,1.0,1811.0,MKE,13342,...,NaN,1209,F9,TPA,15304,"Tampa, FL",Florida,NaN,NaN,NaN
13,15.0,15.0,2314.0,8.0,1,8.0,8.0,2115.0,LAS,12889,...,7.0,1099,F9,MKE,13342,"Milwaukee, WI",Wisconsin,0.0,NaN,0.0
14,-10.0,0.0,1409.0,NaN,1,-2.0,0.0,939.0,CVG,11193,...,NaN,1158,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN,NaN
15,124.0,124.0,1913.0,0.0,1,128.0,128.0,1718.0,LGA,12953,...,124.0,1158,F9,CVG,11193,"Cincinnati, OH",Kentucky,0.0,NaN,0.0
16,78.0,78.0,2211.0,0.0,1,113.0,113.0,1952.0,ATL,10397,...,0.0,1465,F9,LGA,12953,"New York, NY",New York,0.0,NaN,0.0
17,-17.0,0.0,814.0,NaN,1,-7.0,0.0,623.0,DEN,11292,...,NaN,295,F9,TPA,15304,"Tampa, FL",Florida,NaN,NaN,NaN
18,-23.0,0.0,1142.0,NaN,1,-8.0,0.0,1039.0,PSP,14262,...,NaN,429,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN,NaN
19,198.0,198.0,1922.0,198.0,1,219.0,219.0,1634.0,DEN,11292,...,0.0,398,F9,PSP,14262,"Palm Springs, CA",California,0.0,NaN,0.0
20,-28.0,0.0,1035.0,NaN,1,-1.0,0.0,644.0,MIA,13303,...,NaN,1508,F9,MKE,13342,"Milwaukee, WI",Wisconsin,NaN,NaN,NaN
21,-33.0,0.0,1442.0,NaN,1,-14.0,0.0,1144.0,DTW,11433,...,NaN,1323,F9,MIA,13303,"Miami, FL",Florida,NaN,NaN,NaN
22,-32.0,0.0,1849.0,NaN,1,-8.0,0.0,1557.0,MIA,13303,...,NaN,1324,F9,DTW,11433,"Detroit, MI",Michigan,NaN,NaN,NaN
23,-11.0,0.0,2230.0,NaN,1,0.0,0.0,2010.0,MKE,13342,...,NaN,1511,F9,MIA,13303,"Miami, FL",Florida,NaN,NaN,NaN
24,5.0,5.0,1103.0,NaN,1,-1.0,0.0,829.0,SFO,14771,...,NaN,1533,F9,ATL,10397,"Atlanta, GA",Georgia,NaN,NaN,NaN
25,-18.0,0.0,1511.0,NaN,1,-3.0,0.0,1145.0,DEN,11292,...,NaN,658,F9,SFO,14771,"San Francisco, CA",California,NaN,NaN,NaN
26,-21.0,0.0,2149.0,NaN,1,-4.0,0.0,1615.0,MIA,13303,...,NaN,614,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN,NaN
27,-26.0,0.0,106.0,NaN,1,-1.0,0.0,2259.0,DEN,11292,...,NaN,619,F9,MIA,13303,"Miami, FL",Florida,NaN,NaN,NaN
28,13.0,13.0,1133.0,NaN,1,-8.0,0.0,656.0,TPA,15304,...,NaN,1236,F9,MSP,13487,"Minneapolis, MN",Minnesota,NaN,NaN,NaN
29,-11.0,0.0,1356.0,NaN,1,0.0,0.0,1210.0,MCI,13198,...,NaN,1211,F9,TPA,15304,"Tampa, FL",Florida,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644643,53.0,53.0,2017.0,19.0,7,73.0,73.0,1910.0,ORD,13930,...,0.0,2356,AA,RDU,14492,"Raleigh/Durham, NC",North Carolina,0.0,NaN,23.0
644644,15.0,15.0,1939.0,0.0,7,19.0,19.0,1816.0,ORD,13930,...,0.0,2356,AA,RDU,14492,"Raleigh/Durham, NC",North Carolina,0.0,NaN,0.0
644645,1.0,1.0,1925.0,NaN,7,-1.0,0.0,1755.0,ORD,13930,...,NaN,2356,AA,RDU,14492,"Raleigh/Durham, NC",North Carolina,NaN,NaN,NaN
644646,50.0,50.0,1522.0,50.0,7,53.0,53.0,1343.0,SLC,14869,...,0.0,2357,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,0.0,NaN,0.0
644647,-10.0,0.0,1422.0,NaN,7,-2.0,0.0,1248.0,SLC,14869,...,NaN,2357,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,NaN,NaN,NaN
644648,102.0,102.0,1614.0,102.0,7,112.0,112.0,1442.0,SLC,14869,...,0.0,2357,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,0.0,NaN,0.0
644649,-8.0,0.0,1427.0,NaN,7,-4.0,0.0,1246.0,SLC,14869,...,NaN,2357,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,NaN,NaN,NaN
644650,17.0,17.0,1931.0,0.0,7,34.0,34.0,1604.0,DFW,11298,...,0.0,2357,AA,SLC,14869,"Salt Lake City, UT",Utah,0.0,NaN,0.0
644651,121.0,121.0,2115.0,0.0,7,60.0,60.0,1630.0,DFW,11298,...,121.0,2357,AA,SLC,14869,"Salt Lake City, UT",Utah,0.0,NaN,0.0
644652,66.0,66.0,2020.0,0.0,7,85.0,85.0,1655.0,DFW,11298,...,0.0,2357,AA,SLC,14869,"Salt Lake City, UT",Utah,0.0,NaN,0.0
644653,-12.0,0.0,1902.0,NaN,7,-3.0,0.0,1530.0,DFW,11298,...,NaN,2357,AA,SLC,14869,"Salt Lake City, UT",Utah,NaN,NaN,NaN
644654,-16.0,0.0,1048.0,NaN,7,-6.0,0.0,524.0,ORD,13930,...,NaN,2358,AA,TUS,15376,"Tucson, AZ",Arizona,NaN,NaN,NaN
644655,6.0,6.0,1110.0,NaN,7,13.0,13.0,543.0,ORD,13930,...,NaN,2358,AA,TUS,15376,"Tucson, AZ",Arizona,NaN,NaN,NaN
644656,-17.0,0.0,1047.0,NaN,7,-1.0,0.0,529.0,ORD,13930,...,NaN,2358,AA,TUS,15376,"Tucson, AZ",Arizona,NaN,NaN,NaN
644657,-1.0,0.0,1103.0,NaN,7,-7.0,0.0,533.0,ORD,13930,...,NaN,2358,AA,TUS,15376,"Tucson, AZ",Arizona,NaN,NaN,NaN
644658,9.0,9.0,1847.0,NaN,7,11.0,11.0,1526.0,JAX,12451,...,NaN,2360,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,NaN,NaN,NaN
644659,14.0,14.0,1852.0,NaN,7,27.0,27.0,1542.0,JAX,12451,...,NaN,2360,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,NaN,NaN,NaN
644660,3.0,3.0,1841.0,NaN,7,1.0,1.0,1516.0,JAX,12451,...,NaN,2360,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,NaN,NaN,NaN
644661,-13.0,0.0,2010.0,NaN,7,-1.0,0.0,1904.0,LAX,12892,...,NaN,2360,AA,DFW,11298,"Dallas/Fort Worth, TX",Texas,NaN,NaN,NaN
644662,0.0,0.0,2109.0,NaN,7,3.0,3.0,1931.0,DFW,11298,...,NaN,2360,AA,JAX,12451,"Jacksonville, FL",Florida,NaN,NaN,NaN
644663,40.0,40.0,2149.0,0.0,7,28.0,28.0,1956.0,DFW,11298,...,36.0,2360,AA,JAX,12451,"Jacksonville, FL",Florida,0.0,NaN,0.0
644664,-11.0,0.0,2058.0,NaN,7,-3.0,0.0,1925.0,DFW,11298,...,NaN,2360,AA,JAX,12451,"Jacksonville, FL",Florida,NaN,NaN,NaN
644665,0.0,0.0,1607.0,NaN,7,1.0,1.0,801.0,MCO,13204,...,NaN,2361,AA,LAX,12892,"Los Angeles, CA",California,NaN,NaN,NaN
644666,5.0,5.0,1612.0,NaN,7,-6.0,0.0,754.0,MCO,13204,...,NaN,2361,AA,LAX,12892,"Los Angeles, CA",California,NaN,NaN,NaN
644667,-17.0,0.0,1550.0,NaN,7,-1.0,0.0,759.0,MCO,13204,...,NaN,2361,AA,LAX,12892,"Los Angeles, CA",California,NaN,NaN,NaN
644668,53.0,53.0,1710.0,37.0,7,37.0,37.0,847.0,MCO,13204,...,16.0,2361,AA,LAX,12892,"Los Angeles, CA",California,0.0,NaN,0.0
644669,-5.0,0.0,4.0,NaN,7,-2.0,0.0,2133.0,DCA,11278,...,NaN,2362,AA,MIA,13303,"Miami, FL",Florida,NaN,NaN,NaN
644670,54.0,54.0,103.0,54.0,7,63.0,63.0,2238.0,DCA,11278,...,0.0,2362,AA,MIA,13303,"Miami, FL",Florida,0.0,NaN,0.0
644671,-12.0,0.0,2357.0,NaN,7,-1.0,0.0,2134.0,DCA,11278,...,NaN,2362,AA,MIA,13303,"Miami, FL",Florida,NaN,NaN,NaN
644672,-7.0,0.0,6.0,NaN,7,-2.0,0.0,2133.0,DCA,11278,...,NaN,2362,AA,MIA,13303,"Miami, FL",Florida,NaN,NaN,NaN

In [97]:
# df = pd.read_csv("../flight_info_2018.csv")

# df.head()

In [98]:
len(df)

7272370

In [100]:
df.count()

ARR_DELAY              7130071
ARR_DELAY_NEW          7130071
ARR_TIME               7148852
CARRIER_DELAY          1400632
DAY_OF_WEEK            7272370
DEP_DELAY              7150656
DEP_DELAY_NEW          7150656
DEP_TIME               7156199
DEST                   7272370
DEST_AIRPORT_ID        7272370
DEST_CITY_NAME         7272370
DEST_STATE_NM          7272370
FL_DATE                7272370
LATE_AIRCRAFT_DELAY    1400632
NAS_DELAY              1400632
OP_CARRIER_FL_NUM      7272370
OP_UNIQUE_CARRIER      7272370
ORIGIN                 7272370
ORIGIN_AIRPORT_ID      7272370
ORIGIN_CITY_NAME       7272370
ORIGIN_STATE_NM        7272370
SECURITY_DELAY         1400632
Unnamed: 23                  0
WEATHER_DELAY          1400632
dtype: int64

In [127]:


# df.OP_UNIQUE_CARRIER(dtype)


old = pd.DataFrame(zip(df.OP_UNIQUE_CARRIER))
old
# old.to_csv("old_carriers")

          0
0        F9
1        F9
2        F9
3        F9
4        F9
5        F9
6        F9
7        F9
8        F9
9        F9
10       F9
11       F9
12       F9
13       F9
14       F9
15       F9
16       F9
17       F9
18       F9
19       F9
20       F9
21       F9
22       F9
23       F9
24       F9
25       F9
26       F9
27       F9
28       F9
29       F9
...      ..
7272340  AA
7272341  AA
7272342  AA
7272343  AA
7272344  AA
7272345  AA
7272346  AA
7272347  AA
7272348  AA
7272349  AA
7272350  AA
7272351  AA
7272352  AA
7272353  AA
7272354  AA
7272355  AA
7272356  AA
7272357  AA
7272358  AA
7272359  AA
7272360  AA
7272361  AA
7272362  AA
7272363  AA
7272364  AA
7272365  AA
7272366  AA
7272367  AA
7272368  AA
7272369  AA

[7272370 rows x 1 columns]

In [128]:


print(df['OP_UNIQUE_CARRIER'].unique())

['F9' 'EV' 'G4' 'HA' 'MQ' 'NK' 'OH' 'OO' 'WN' 'YV' 'YX' 'AA' 'AS' 'DL'
 '9E' 'B6' 'UA' 'VX']

In [106]:

df.head()
#preview the dataframe
df = df.drop(['Unnamed: 23'], axis=1)
df.head()

,ARR_DELAY,ARR_DELAY_NEW,ARR_TIME,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_DELAY_NEW,DEP_TIME,DEST,DEST_AIRPORT_ID,...,LATE_AIRCRAFT_DELAY,NAS_DELAY,OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,SECURITY_DELAY,WEATHER_DELAY
0,-1.0,0.0,417.0,NaN,1,-1.0,0.0,54.0,DEN,11292,...,NaN,NaN,408,F9,LAX,12892,"Los Angeles, CA",California,NaN,NaN
1,-32.0,0.0,933.0,NaN,1,-7.0,0.0,623.0,ORD,13930,...,NaN,NaN,1286,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN
2,5.0,5.0,824.0,NaN,1,22.0,22.0,622.0,LAS,12889,...,NaN,NaN,1679,F9,MCO,13204,"Orlando, FL",Florida,NaN,NaN
3,7.0,7.0,1436.0,NaN,1,2.0,2.0,912.0,MEM,13244,...,NaN,NaN,1990,F9,LAS,12889,"Las Vegas, NV",Nevada,NaN,NaN
4,212.0,212.0,2029.0,210.0,1,213.0,213.0,1852.0,LAS,12889,...,2.0,0.0,1999,F9,MEM,13244,"Memphis, TN",Tennessee,0.0,0.0

In [107]:
#fillna with 0

df[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY"]] =  df[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY"]].fillna(value=0)



df.head()

,ARR_DELAY,ARR_DELAY_NEW,ARR_TIME,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_DELAY_NEW,DEP_TIME,DEST,DEST_AIRPORT_ID,...,LATE_AIRCRAFT_DELAY,NAS_DELAY,OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,SECURITY_DELAY,WEATHER_DELAY
0,-1.0,0.0,417.0,NaN,1,-1.0,0.0,54.0,DEN,11292,...,NaN,NaN,408,F9,LAX,12892,"Los Angeles, CA",California,NaN,NaN
1,-32.0,0.0,933.0,NaN,1,-7.0,0.0,623.0,ORD,13930,...,NaN,NaN,1286,F9,DEN,11292,"Denver, CO",Colorado,NaN,NaN
2,5.0,5.0,824.0,NaN,1,22.0,22.0,622.0,LAS,12889,...,NaN,NaN,1679,F9,MCO,13204,"Orlando, FL",Florida,NaN,NaN
3,7.0,7.0,1436.0,NaN,1,2.0,2.0,912.0,MEM,13244,...,NaN,NaN,1990,F9,LAS,12889,"Las Vegas, NV",Nevada,NaN,NaN
4,212.0,212.0,2029.0,210.0,1,213.0,213.0,1852.0,LAS,12889,...,2.0,0.0,1999,F9,MEM,13244,"Memphis, TN",Tennessee,0.0,0.0

In [79]:
len(df)

7272370

In [108]:
#reshaping

X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
print(X.shape, y.shape)

(7272370, 5) (7272370, 1)

In [109]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dfle = df
dfle.OP_UNIQUE_CARRIER = le.fit_transform(dfle.OP_UNIQUE_CARRIER)

dfle.head()

,ARR_DELAY,ARR_DELAY_NEW,ARR_TIME,CARRIER_DELAY,DAY_OF_WEEK,DEP_DELAY,DEP_DELAY_NEW,DEP_TIME,DEST,DEST_AIRPORT_ID,...,LATE_AIRCRAFT_DELAY,NAS_DELAY,OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER,ORIGIN,ORIGIN_AIRPORT_ID,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,SECURITY_DELAY,WEATHER_DELAY
0,-1.0,0.0,417.0,NaN,1,-1.0,0.0,54.0,DEN,11292,...,NaN,NaN,408,6,LAX,12892,"Los Angeles, CA",California,NaN,NaN
1,-32.0,0.0,933.0,NaN,1,-7.0,0.0,623.0,ORD,13930,...,NaN,NaN,1286,6,DEN,11292,"Denver, CO",Colorado,NaN,NaN
2,5.0,5.0,824.0,NaN,1,22.0,22.0,622.0,LAS,12889,...,NaN,NaN,1679,6,MCO,13204,"Orlando, FL",Florida,NaN,NaN
3,7.0,7.0,1436.0,NaN,1,2.0,2.0,912.0,MEM,13244,...,NaN,NaN,1990,6,LAS,12889,"Las Vegas, NV",Nevada,NaN,NaN
4,212.0,212.0,2029.0,210.0,1,213.0,213.0,1852.0,LAS,12889,...,2.0,0.0,1999,6,MEM,13244,"Memphis, TN",Tennessee,0.0,0.0

In [130]:
print(dfle['OP_UNIQUE_CARRIER'].unique())

[ 6  5  7  8  9 10 11 12 15 16 17  1  2  4  0  3 13 14]

In [111]:
#reshaping

X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
print(X.shape, y.shape)

(7272370, 5) (7272370, 1)

In [112]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

In [113]:
# Split the data into training and testing

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [115]:
X_test

,DAY_OF_WEEK,DEP_TIME,ORIGIN_AIRPORT_ID,OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER
236666,3,1954.0,10821,301,15
408419,5,832.0,13303,2537,1
85932,1,1430.0,12451,2342,4
393447,5,1511.0,10397,2591,4
93571,2,1844.0,15016,18,4
68433,1,1138.0,15919,3604,17
439718,6,1414.0,12892,1257,4
333012,4,649.0,13487,4746,12
553869,6,1159.0,13198,2812,15
33926,1,1620.0,11298,2418,1
469162,6,715.0,13796,6419,15
432565,6,2014.0,14492,5281,15
100001,2,1139.0,11252,500,3
481573,6,1910.0,13796,4927,15
52681,1,1840.0,11298,2408,1
229485,3,1239.0,12953,3347,0
338300,4,2046.0,10821,1233,4
98599,1,1658.0,13796,3522,15
201860,3,614.0,12889,1009,15
89684,2,1907.0,12451,3485,9
265077,3,1709.0,11278,5180,0
237626,3,1903.0,11259,173,15
228693,3,1905.0,10397,1777,4
440947,5,1958.0,12953,556,13
136532,2,1126.0,15412,3139,12
613880,7,804.0,11292,598,13
454740,6,1427.0,13061,3941,9
251085,4,1152.0,10980,3521,12
107639,2,2157.0,14869,7397,12
142203,2,2225.0,10821,5467,15
...,...,...,...,...,...
473781,6,1743.0,11775,5835,16
104400,2,745.0,15304,1369,1
25803,1,1744.0,10792,295,15
12899,1,2310.0,14747,660,2
248942,4,658.0,10693,2297,1
219445,3,1444.0,11057,5104,11
379559,4,2028.0,13930,3053,12
320832,4,910.0,10721,5969,15
404072,5,2000.0,14635,140,15
320904,4,622.0,11697,2777,1
365039,5,1931.0,11618,677,13
396337,5,1751.0,13930,5066,12
157479,2,1844.0,12889,915,15
71685,1,0.0,11066,588,1
255590,4,756.0,14685,3359,9
352882,4,909.0,11298,2521,1
249892,3,1914.0,12953,521,4
583328,7,1745.0,10397,2496,4
92959,2,1613.0,14683,2224,4
584146,7,1750.0,11292,3747,15
250409,3,2119.0,10397,2284,4
353911,5,1146.0,14747,4737,12
550905,7,1034.0,13930,5217,12
124659,2,1109.0,11292,5123,12
505361,6,1135.0,11995,3506,9
518782,6,1326.0,13541,4605,17
222402,3,2325.0,10397,2043,4
371216,5,1757.0,13198,1906,1
84932,2,2143.0,13930,1250,13
528412,6,1412.0,14262,1056,2

In [123]:
X_test[0:1000]

,DAY_OF_WEEK,DEP_TIME,ORIGIN_AIRPORT_ID,OP_CARRIER_FL_NUM,OP_UNIQUE_CARRIER
236666,3,1954.0,10821,301,15
408419,5,832.0,13303,2537,1
85932,1,1430.0,12451,2342,4
393447,5,1511.0,10397,2591,4
93571,2,1844.0,15016,18,4
68433,1,1138.0,15919,3604,17
439718,6,1414.0,12892,1257,4
333012,4,649.0,13487,4746,12
553869,6,1159.0,13198,2812,15
33926,1,1620.0,11298,2418,1
469162,6,715.0,13796,6419,15
432565,6,2014.0,14492,5281,15
100001,2,1139.0,11252,500,3
481573,6,1910.0,13796,4927,15
52681,1,1840.0,11298,2408,1
229485,3,1239.0,12953,3347,0
338300,4,2046.0,10821,1233,4
98599,1,1658.0,13796,3522,15
201860,3,614.0,12889,1009,15
89684,2,1907.0,12451,3485,9
265077,3,1709.0,11278,5180,0
237626,3,1903.0,11259,173,15
228693,3,1905.0,10397,1777,4
440947,5,1958.0,12953,556,13
136532,2,1126.0,15412,3139,12
613880,7,804.0,11292,598,13
454740,6,1427.0,13061,3941,9
251085,4,1152.0,10980,3521,12
107639,2,2157.0,14869,7397,12
142203,2,2225.0,10821,5467,15
...,...,...,...,...,...
429297,5,1348.0,13930,602,1
326723,4,1406.0,11995,1749,4
394247,5,841.0,10821,934,15
439671,5,525.0,12217,2979,4
449078,5,844.0,12953,5893,17
293229,4,0.0,12191,282,3
526288,6,2124.0,11618,1526,13
82607,1,1323.0,14100,4423,17
530796,6,706.0,14492,683,1
403655,6,1216.0,13296,5502,11
450837,5,1858.0,13930,3692,9
179398,2,1252.0,14831,1429,4
396903,5,2242.0,14679,1334,15
282079,4,2011.0,14869,1346,4
380721,5,1230.0,10821,324,15
202379,3,851.0,13232,1593,15
194779,3,1600.0,12889,1357,15
86977,1,704.0,14492,1097,4
549168,7,1419.0,11697,181,3
224182,3,2354.0,14869,2995,4
309601,4,935.0,11057,5289,11
209351,3,2046.0,13930,3561,9
579959,7,1141.0,10693,3929,15
347859,5,532.0,14747,1922,15
35233,1,651.0,12266,200,10
103371,2,1458.0,13485,4166,9
218340,3,1345.0,14112,908,7
504455,6,1309.0,14100,1848,1
46467,1,1007.0,11259,6004,15
517297,6,1853.0,14635,1035,1

In [117]:
# Create a LinearRegression model and fit it to  training data

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [119]:


# predictions
# PREDICT DEP_DELAY in minutes

abb_X = X_test[0:10]
predictions = model.predict(abb_X)


predictions

array([[18.32288379],
       [ 4.00512231],
       [12.128618  ],
       [12.71115677],
       [16.45147299],
       [ 8.70641863],
       [10.90813156],
       [ 2.499235  ],
       [ 8.23672039],
       [14.52065543]])

In [120]:



model.coef_

# X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
# y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
# print(X.shape, y.shape)

array([[-1.61285738e-01,  1.23154521e-02, -9.23434461e-05,
         1.62476554e-04,  2.22395619e-02]])

In [121]:
model.intercept_

array([-4.64090288])

In [122]:
model.predict([[1,702,11986,14107,6]])

array([[5.16192434]])

In [ ]:
model.predict([[1,702,1074,14107,1074,6]])


DAY_OF_WEEK		d --OP_UNIQUE_CARRIER	OP_CARRIER_FL_NUM	ORIGIN_AIRPORT_ID	DEST_AIRPORT_ID	DEST	DEP_TIME	DEP_DELAY
1		AS	1	11278	14747	SEA	757	-3
1	2019-01-07	F9	1074	14107	11986	GRR	702	-8

In [ ]:
X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
model.predict([[1,702,11986,14107,6]])